LearnUsers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/pokecards/', permanent=True)),
    url(r'^pokecards/', include('pokecards.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

pokecards/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mycards/$', views.MyCardInstancesListView.as_view(), name='my-cards'),
    url(r'^cardinstances/(?P<pk>[-\w]+)', views.CardInstanceDetailView.as_view(), name='cardinstance-detail'),
    url(r'^cards/$', views.AllCardsView.as_view(), name='all-cards'),
    url(r'^cards/(?P<pk>\d+)$', views.CardDetailView.as_view(), name='card-detail'),
    url(r'^cards/create/', views.create_card, name='create-card'),
    url(r'^cards/ajax_create_card/', views.ajax_create_card, name='ajax-create-card'),
    url(r'^cards/character-available/', views.ajax_char_available, name='character-available'),
]

pokecards/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
import uuid


class Card(models.Model):
    character = models.CharField(max_length=100)
    static_image_path = models.CharField(max_length=200, default='images/logo.png')

    def __str__(self):
        return self.character


class CardInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular card instance")
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    card = models.ForeignKey(Card, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        if self.owner:
            return 'Card type %s; owned by %s' % (self.card.character, self.owner.get_username())
        else:
            return 'Card type %s; unowned' % self.card.character

pokecards/views.py
from django.shortcuts import render
from django.views import generic
from .models import CardInstance, Card
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse


def index(request):
    return render(request, 'pokecards/index.html', {'name': 'edwin'})


class MyCardInstancesListView(LoginRequiredMixin, generic.ListView):
    model = CardInstance
    template_name = 'pokecards/my_cards.html'
    paginate_by = 5

    def get_queryset(self):
        return CardInstance.objects.filter(owner=self.request.user)


class CardInstanceDetailView(generic.DetailView):
    model = CardInstance
    template_name = 'pokecards/instance_detail_view.html'


class AllCardsView(generic.ListView):
    model = Card
    template_name = 'pokecards/all_cards.html'
    paginate_by = 5

    def get_queryset(self):
        return Card.objects.order_by('character')


class CardDetailView(generic.DetailView):
    model = Card
    template_name = 'pokecards/detail_view.html'


@login_required
def create_card(request):
    if not request.method == "POST":
        return JsonResponse({'message': u"Only accepts POST requests"}, status=405)
    post = request.POST.copy()
    if 'character' in post and 'image_path' in post:
        if Card.objects.filter(character=post['character']).count() > 0:
            return JsonResponse({'message': u"Character name already in use."}, status=400)
        new_char = Card.objects.create(character=post['character'], static_image_path=post['image_path'])
        return HttpResponseRedirect(reverse('card-detail', args=[new_char.id]))
    else:
        return JsonResponse({'message': u"Insufficient POST data (need 'character' and 'image_path')"}, status=400)


@login_required
def ajax_create_card(request):
    if not request.method == "POST":
        return JsonResponse({'message': u"Only accepts POST requests"}, status=405)
    post = request.POST.copy()
    if 'character' in post and 'image_path' in post:
        if Card.objects.filter(character=post['character']).count() > 0:
            return JsonResponse({'message': u"Character name already in use."}, status=400)
        else:
            Card.objects.create(character=post['character'], static_image_path=post['image_path'])
            return JsonResponse({'character': post['character'], 'image_path': post['image_path']})
    else:
        return JsonResponse({'msg': u"Requires both 'slug' and 'title'!"}, status=400)


def ajax_char_available(request):
    if not request.method == 'GET':
        return JsonResponse({'message': u"Only accepts GET requests"}, status=405)
    if 'character' in request.GET:
        if Card.objects.filter(character=request.GET['character']).count() == 0:
            return JsonResponse(data={'available': 'true'})
        else:
            return JsonResponse(data={'available': 'false'})

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Our Website</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-header">
                <a href="{% url 'index' %}" class="pull-left"><img src="{% static 'images/logo.png' %}"
                                                                   style="width:50px;"></a>
            </div>
{#            <a class="navbar-brand" href="#">PokeSiteStuff</a>#}
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="{% url 'all-cards' %}">All Cards</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'my-cards' %}">My Cards</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#"><span
                            class="glyphicon glyphicon-user"></span> User: {{ user.get_username }}</a></li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}"><span
                            class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}"><span
                            class="glyphicon glyphicon-log-in"></span>
                        Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-6">
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                             {% if page_obj.has_previous %}
                                 <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&#x226a;</a>
                             {% endif %}
                            <span class="page-current">
                                 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                             </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">&#x226b;</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>
</div>

<hr>

{% block addnewcard %}{% endblock %}

</body>
</html>

templates/pokecards/all_cards.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h1>Manage Cards</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h3>All Known Cards</h3>
                {% if card_list %}
                    <div id="cards" class="list-group">
                        {% for card in card_list %}
                            <a class="list-group-item" href="{% url 'card-detail' card.pk %}">
                                {{ card.character }}<span class="badge">{{ card.cardinstance_set.count }}</span>
                            </a>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>No Known Cards.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block addnewcard %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h3>Create New Card</h3>
                <form class="form-horizontal" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="character" class="col-sm-2 control-label">Character Name</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="character"
                                   placeholder="Enter Character Name (Pikachu)">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="image_path" class="col-sm-2 control-label">Last Name</label>

                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="image_path"
                                   placeholder="/images/pikachu.png">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default" id="create">Create character</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        var display_error = function (msg, elem) {
            var msg_div = $('<div class="error_msg"><p>' + msg + '</p></div>');
            msg_div.insertAfter(elem).fadeIn('slow').animate({opacity: 1.0}, 3000).fadeOut('slow', function () {
                msg_div.remove();
            });
        };
        var create_note = function () {
            {% if user.is_authenticated %}
                var character = $("#character").val();
                var image_path = $("#image_path").val();
                if (character != "" && image_path != "") {
                    var data = {character: character, image_path: image_path, csrfmiddlewaretoken: '{{ csrf_token }}'};
                    var args = {type: "POST", url: "ajax_create_card/", data: data, complete: done};
                    $.ajax(args);
                }
                else {
                    // display an explanation of failure
                }
                return false;
            {% else %}
                display_error("Must be logged in to add a new card!", $("#create"));
                return false;
            {% endif %}
        };
        var done = function (res, status) {
            if (status == "success") {
                var txt = res.responseText;
                var obj = JSON.parse(txt);
                var character = obj.character;
                var image_path = obj.image_path;
                var newLi = $('<li class="list-group-item"><b>' + character + '</b></li>');
                $("#cards").prepend(newLi);
                $("#character").val("");
                $("#image_path").val("");
            }
            else {
                display_error("Only works for logged in users, are you sure you are logged in?.", $("#create"));
            }
        };
        $("#create").click(create_note);
        $("#character").keyup(function () {
            var char = this.value;
            var complete = function (res, status) {
                var response = JSON.parse(res.responseText);
                if (status == "success") {
                    if (response.available == "true") {
                        $("#character").css('background-color', 'white');
                    } else {
                        $("#character").css('background-color', '#FFA0A0');
                    }
                } else {
                    display_error("Something went wrong with the server!", $("#create"));
                }
            };
            $.ajax({type: 'GET', url: 'character-available/', data: {'character': char}, complete: complete});
        });
    </script>
{% endblock %}

templates/pokecards/detail_view.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h1>Card Details</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h3>{{ card.character }}</h3>
                {% load static %}
                <img src="{% static card.static_image_path %}" alt="My image" style="width:200px;"/>
                <hr>
                <h3>Instances</h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Owner</th>
                            <th>UUID</th>
                            <th>Link to Instance</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for inst in card.cardinstance_set.all %}
                            <tr>
                                <td>{{ inst.owner }}</td>
                                <td>{{ inst.id }}</td>
                                <td><a href="{% url 'cardinstance-detail' inst.id %}">Instance</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/pokecards/index.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h1>Home Page!</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h3>Status</h3>
                <p>This is the beginning of a Pokecard based website.</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/pokecards/instance_detail_view.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h1>Card Instance Details</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                {% load static %}
                <img src="{% static cardinstance.card.static_image_path %}" alt="My image" style="width:200px;"/>
                <hr>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Character</th>
                            <th>UUID</th>
                            <th>Owner</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><a href="{% url 'card-detail' cardinstance.card.pk %}">{{ cardinstance.card.character }}</a></td>
                            <td>{{ cardinstance.id }}</td>
                            <td>{{ cardinstance.owner }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/pokecards/my_cards.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h1>My Own Cards</h1>
            </div>
        </div>
    </div>
    <hr>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">
                <h3>My Cards</h3>
                {% if cardinstance_list %}
                    <div id="cards" class="list-group">
                        {% for cardinst in cardinstance_list %}
                            <a class="list-group-item" href="{% url 'cardinstance-detail' cardinst.id %}">
                                {{cardinst.card.character}} ({{ cardinst.id }})
                            </a>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>You don't have any cards.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}